### PR TITLE
feat(dump history): You can specify the time range, regex and format to dump

### PR DESCRIPTION
**Pull request by TD-Sky**
Implementation of https://github.com/cantino/mcfly/issues/372.

Now you can dump the history. For example,

```bash
$ mcfly dump > history.json
```

will dump the whole history into json file.

Here are the options:

```
      --since <SINCE>    Select all commands ran since the point
      --before <BEFORE>  Select all commands ran before the point
  -s, --sort <ORDER>     Sort order [case ignored] [default: ASC] [possible values: ASC, DESC]
  -r, --regex <REGEX>    Require commands to match the pattern
  -f, --format <FORMAT>  The format to dump in [default: json] [possible values: json, csv]
  -h, --help             Print help
```

The timestamp (since/before) format is subject to [chrono-systemd-time](https://docs.rs/chrono-systemd-time-ng/latest/chrono_systemd_time/) which is a non-strict implementation of [systemd.time](https://www.freedesktop.org/software/systemd/man/systemd.time.html).

---

I think the PR isn't in the final stage now so suggestions are welcome.

### CODE REVIEW

**Comment by cantino** [comment]
Awesome, I'll test this out shortly. Thanks @TD-Sky

**Comment by cantino** [comment]
@TD-Sky would you be able to also update the `mcfly help dump` page and README with example usage and especially a timestamp example or format reference?

**Comment by TD-Sky** [comment]
Let me have a try.

**Comment by TD-Sky** [comment]
You could review README.md now.

Sorry for my delay, I'm busy these days.

**Comment by Houlistonm** [comment]
Any plans to merge?

**Comment by TD-Sky** [comment]
> Any plans to merge?

`chrono` depreciated some APIs we are using. I may need to refactor `chrono-systemd-time` to adapt the correct APIs.

**Comment by TD-Sky** [comment]
Fixed.

**Review by cantino — APPROVED** [review]

**Comment by cantino** [comment]
Released https://github.com/cantino/mcfly/releases/tag/v0.8.3

**Pull request merged**
