### PR TITLE
Remove unnecessary/unused regex features

### PR DESCRIPTION
**Pull request by jirutka**
To reduce binary size.

### CODE REVIEW

**Comment by cantino** [comment]
Does this have any other impact on our regex that I should be aware of besides removing `\d`? How significant is the size reduction?

**Comment by jirutka** [comment]
> Does this have any other impact on our regex that I should be aware of besides removing \d?

No, not on the regexes you currently use.

> How significant is the size reduction?

About 400–500 kiB for the release build.

**Comment by cantino** [comment]
Thanks!

**Comment by cantino** [comment]
Released in https://github.com/cantino/mcfly/releases/tag/v0.8.1

**Pull request merged**
