### PR TITLE
Add customizable prompt with $MCFLY_PROMPT

### LINKED ISSUE #324: Customize Prompt?
Is it possible to change the `$` prompt to something custom, perhaps through and environment variable? I'd like to have it match my shell prompt. Sorry if this has been asked before, all I could find was something about `PROMPT_COMMAND` but that did not seem to be relevant.

### PR DESCRIPTION
**Pull request by vedkothavade**
If `MCFLY_PROMPT` is set, it is used as the prompt, but if not it defaults to `$`. Fixes #324.

### CODE REVIEW

**Comment by cantino** [comment]
This looks great, thanks @vedkothavade!

**Comment by cantino** [comment]
Actually, I did find a bug. Try setting `MCFLY_PROMPT='>>>'`, or anything longer than 2 characters.

**Comment by vedkothavade** [comment]
> Actually, I did find a bug. Try setting `MCFLY_PROMPT='>>>'`, or anything longer than 2 characters.

I missed that, added a check for the prompt length

**Comment by cantino** [comment]
Thanks @vedkothavade!

**Comment by cantino** [comment]
Released in v0.8.0.

**Pull request merged**
