### PR TITLE
Add a new config to delete entry without confirm.

### PR DESCRIPTION
**Pull request by goddade**
Signed-off-by: loRe <goddade@gmail.com>

### CODE REVIEW

**Comment by cantino** [comment]
Thanks @goddade! Can you please run this through cargo clippy and cargo fmt?

**Comment by cantino** [comment]
Thanks @goddade!

**Comment by cantino** [comment]
Released in https://github.com/cantino/mcfly/releases/tag/v0.5.8!

**Comment by dasebasto** [comment]
It works as expected when running `mcfly "search --delete_without_confirm`, but how do I enable this option for the regular mcfly widget (Ctrl-R) ?

**Pull request merged**
